config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :books, only: [:index, :show]
  resources :authors, only: [:index, :show]

  namespace :admin do
    resources :books, only: [:new, :create, :edit, :update, :destroy]
    resources :authors, only: [:new, :create, :edit, :update, :destroy]
    resources :dashboard, only: [:index] do
      collection do
        post :upload
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books
  has_many :author_genres
  has_many :genres, through: :author_genres

  validates :name, presence: true
  # validates :about, presence: true
  validates :photo, presence: true
end

app/models/author_genre.rb
class AuthorGenre < ApplicationRecord
  belongs_to :author
  belongs_to :genre
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  
  has_many :book_genres
  has_many :genres, through: :book_genres

  validates :title, presence: true
  validates :description, presence: true
  validates :cover_image, presence: true
  validates :year, presence: true
  validates :price, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :authors
  has_many :books, through: :authors
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum access: { 
    user: 0, 
    admin: 1 
  }
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  def index
    @users = User.all
    @number_of_books = Book.count

    @number_of_authors = Author.count

    @authors = Author.all

    @books = Book.all
  end

  def upload
    @url = params[:url]
    BookScraperJob.perform_later(@url)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit::Authorization

  # Pundit: allow-list approach
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = policy_scope(Book)
  end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/admin/dashboard/index.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-6">
      <div class="d-flex justify-content-between">
        <div class="border border-2 border-primary rounded p-3 w-100 me-2">
          <h1>Authors<h1>
          <p><%= @number_of_authors %></p>
        </div>
        <div class="border border-2 border-primary rounded p-3 w-100">
          <h1>Books<h1>
          <p><%= @number_of_books %></p>
        </div>
      </div>
      <div>
        <table class="table">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Photo</th>
              <th scope="col">Name</th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody>
            <% @authors.each do |author| %>
              <tr>
                <th scope="row"><%= author.id %></th>
                <td><img src="<%= author.photo %>" class="w-25 h-25"></td>
                <td><%= author.name %></td>
                <td><button class="btn btn-primary">Edit</button></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <div class="col-md-6">
      <h1>Dashboard</h1>
      <%= form_with url: upload_admin_dashboard_index_path, method: :post, local: true do |f| %>
        <%= f.text_field :url %>
        <%= f.submit "Scraper" %>
      <% end %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container d-flex">
  <div class="row">
    <% @books.each do |book| %>
      <div class="col-md-3">
        <img class="w-25" src="<%= book.cover_image %>" >
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookstore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>